spring:
  #mysql数据库配置
  r2dbc:
    url: r2dbcs:mysql://localhost:3306/mydb?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: admin
  #swagger配置
  swagger:
    group-name: 员工管理
    title: webflux测试管理
    description: 测试webflux接口
    version: 1.0.0
    terms-of-service-url: http://localhost:8080/doc.html
    base-package: com.clj.webflux.controller

